# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.cache/wt [current_project]
set_property parent.project_path C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
add_files -quiet C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/sources_1/imports/audio_recorder/i2c_controller.v
  C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/sources_1/imports/audio_recorder/sine_wave.v
  C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/sources_1/imports/audio_recorder/i2c_config.v
  C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/sources_1/imports/audio_recorder/freq_div.v
  C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/sources_1/imports/audio_recorder/audio_effects.v
  C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/sources_1/imports/audio_recorder/audio_codec.v
  C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/sources_1/imports/audio_recorder/i2c_top.v
  C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/sources_1/imports/audio_recorder/edge_detect.v
  C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/sources_1/imports/audio_recorder/debounce.v
  C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/sources_1/imports/audio_recorder/recorder.v
  C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/sources_1/imports/import/uart_tx.v
  C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/sources_1/imports/import/uart_rx.v
  C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/sources_1/new/debounce0.v
  C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/sources_1/imports/import/UART_crl.v
  C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/sources_1/imports/import/display.v
  C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/sources_1/imports/import/set_time.v
  C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/sources_1/imports/import/music.v
  C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/sources_1/imports/import/divfreq_1Hz.v
  C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/sources_1/imports/import/blinking.v
  C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/sources_1/new/Clocking.v
  C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/sources_1/imports/sources_1/imports/import/time_transfrom.v
  C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/sources_1/imports/import/top.v
}
read_xdc C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/constrs_1/imports/Desktop/digital_clock.xdc
set_property used_in_implementation false [get_files C:/Users/BME/Desktop/final_work/fwork_all/fwork_all.srcs/constrs_1/imports/Desktop/digital_clock.xdc]

catch { write_hwdef -file top.hwdef }
synth_design -top top -part xc7z020clg484-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
